version: '3'
services:

  api:
    build:
      context: .
    volumes:
      - .:/src
    ports:
      - 8080:80
    networks:
      - backend
    environment:
      CORS_ALLOWED_ORIGINS: "http://localhost:3000"

networks:
  backend: