version: '3'
services:

  api:
    build:
      context: .
    volumes:
      - .:/src
    ports:
      - 8080:80
    networks:
      - backend
    environment:
      CORS_ALLOWED_ORIGIN: http://localhost:3000
      MONGO_DB_CONNECTION_URI: ${MONGO_DB_CONNECTION_URI}
      AUTH0_DOMAIN: https://dev-k1aifjsj.auth0.com/
      API_IDENTIFIER: https://dev-k1aifjsj.auth0.com/api/v2/
      JWT_SIGNING_ALGO: RS256


networks:
  backend:
